import test from 'node:test';import assert from 'node:assert/strict';
import{parsePostUrl,classify,extractEmbed,mergeEvents,validateEvent,evidenceExcerpt}from'../src/evidence.mjs';import{freshness,calendarFile,escapeHtml}from'../src/shared.mjs';import{locales,names}from'../src/locales.mjs';
test('reject impostor sources and script URLs',()=>{for(const url of ['https://x.com.evil.test/OpenAI/status/123','https://x.com/fake/status/123','http://x.com/OpenAI/status/123','javascript:alert(1)'])assert.equal(parsePostUrl(url),null);assert.equal(parsePostUrl('https://x.com/OpenAI/status/123')?.id,'123');});
test('future, completion, credits and incomplete evidence stay separate',()=>{assert.equal(classify('We will do a global reset of Codex usage').state,'announced');assert.equal(classify('We have reset usage for all paid Codex users').state,'reported');assert.equal(classify('We have added banked resets for Codex').kind,'banked');assert.equal(classify('We have reset usage for Codex…',{truncated:true}).state,'unconfirmed');for(const text of ['We will not reset Codex usage','We have not reset Codex usage','If we reset Codex usage, you can work','Someone said we have reset Codex usage','Codex reset is not yet complete'])assert.equal(classify(text).state,'unconfirmed',text);});
test('embed identity checks and encoded text',()=>{const url='https://x.com/OpenAI/status/123';const embed={url,author_url:'https://twitter.com/OpenAI',html:'<p>Codex &amp; usage… <a href="https://t.co/test">https://t.co/test</a></p>'};assert.equal(extractEmbed(embed,url).truncated,true);assert.throws(()=>extractEmbed({...embed,author_url:'https://twitter.com/fake'},url));assert.throws(()=>extractEmbed({...embed,url:'https://x.com/OpenAI/status/124'},url));});
test('health ages without a successful build and never stays falsely green',()=>{const now=Date.now();assert.equal(freshness({lastSuccessAt:new Date(now-4*3600000).toISOString(),status:'ok'},now),'stale');assert.equal(freshness({lastSuccessAt:new Date(now).toISOString(),status:'degraded'},now),'degraded');assert.equal(freshness({status:'ok'},now),'stale');});
test('dedupe and incomplete fallback preserve complete evidence',()=>{const ev={id:'123',sourceUrl:'https://x.com/OpenAI/status/123',kind:'global',state:'reported',publishedAt:'2026-09-01',verifiedAt:'2026-09-02',truncated:false,excerpt:'We have reset Codex usage.',provenance:'x-oembed',rulesVersion:'1.0.0',contentHash:'a'.repeat(64)};assert.equal(mergeEvents([ev],[ev]).length,1);assert.equal(mergeEvents([ev],[{...ev,truncated:true,state:'unconfirmed'}])[0].state,'reported');assert.throws(()=>validateEvent({...ev,truncated:true}));});
test('calendar uses UTC and escapes title instead of injecting properties',()=>{const file=calendarFile(Date.parse('2026-09-10T10:30:00+08:00'),'Check\nATTENDEE:bad');assert.ok(file.includes('DTSTART:20260910T023000Z'));assert.ok(!file.includes('\r\nATTENDEE:'));assert.throws(()=>calendarFile(NaN,'test'));});
test('all nine locales have real copy and text is escaped',()=>{assert.equal(Object.keys(locales).length,9);for(const lang of Object.keys(names))for(const value of Object.values(locales[lang]))assert.ok(typeof value==='string'&&value.length>0);assert.equal(escapeHtml('<script>'),'&lt;script&gt;');assert.ok(evidenceExcerpt('reset '+ 'word '.repeat(80)).split(/\s+/).length<=24);});
