import { readFile, writeFile, mkdir, cp } from 'node:fs/promises';
import { locales, names } from '../src/locales.mjs';
import { CANONICAL, REPO, escapeHtml as e, localePath, eventPath, freshness } from '../src/shared.mjs';
import { validateEvent } from '../src/evidence.mjs';
const root = new URL('../', import.meta.url);
const out = new URL('dist/', root);
const events = JSON.parse(await readFile(new URL('data/events.json', root), 'utf8'));
const health = JSON.parse(await readFile(new URL('data/health.json', root), 'utf8'));
events.forEach(validateEvent);
await mkdir(out, { recursive: true });
await cp(new URL('public/', root), out, { recursive: true, filter: path => !String(path).endsWith('mascot-source.png') });
await mkdir(new URL('assets/', out), { recursive: true });
for (const file of ['app.mjs','style.css','shared.mjs']) await cp(new URL(`src/${file}`, root), new URL(`assets/${file}`, out));
for (const file of ['events.json','health.json']) await cp(new URL(`data/${file}`,root),new URL(file,out));
const write = async (path, text) => {const url = new URL(path, out); await mkdir(new URL('./',url),{recursive:true});await writeFile(url,text);};
const usageUrl = 'https://chatgpt.com/codex/settings/usage';
const guide = 'https://help.openai.com/en/articles/11369540-using-codex-with-your-chatgpt-plan';
const date = (at,lang) => new Intl.DateTimeFormat(lang, { dateStyle:'medium', timeStyle:'short', timeZone:'UTC' }).format(new Date(at)) + ' UTC';
const kindLabel = (ev,t) => t[ev.kind === 'usage' ? 'usageKind' : ev.kind];
const icon = kind => ({global:'↻',banked:'☆',usage:'↗',signal:'·'}[kind] || '↻');
const cursor = '<svg class="brand-icon" viewBox="0 0 28 32" aria-hidden="true"><path d="M3 2v25l6-6 5 9 5-3-5-8h10L3 2Z" fill="currentColor" stroke="var(--ink)" stroke-width="2" stroke-linejoin="round"/></svg>';
function row(ev,lang,base) {const t=locales[lang];return `<article class="event-row" data-kind="${e(ev.kind)}"><div class="event-icon" aria-hidden="true">${icon(ev.kind)}</div><div class="event-main"><div class="event-title"><a href="${base}${eventPath(lang,ev.id)}">${e(kindLabel(ev,t))}</a><span class="badge ${ev.state}">${e(t[ev.state])}</span></div><p class="excerpt" lang="en" dir="ltr">${e(ev.excerpt)}</p><div class="event-meta"><span>@${e(ev.author)}</span><time datetime="${ev.publishedAt}" title="${ev.publishedAt}">${e(date(ev.publishedAt,lang))}</time><a href="${e(ev.sourceUrl)}" target="_blank" rel="noopener noreferrer">${e(t.source)} ↗</a></div></div></article>`;}
function render(lang,ev=null){
const t=locales[lang];const path=ev?eventPath(lang,ev.id):localePath(lang);const base=ev?(lang==='en'?'../../':'../../../'):(lang==='en'?'./':'../');const url=CANONICAL+path;const title=ev?`${kindLabel(ev,t)} · ${t[ev.state]} | Codex Respawn`:`Codex Respawn — ${t.shareTitle}`;
const options=Object.entries(names).map(([code,name])=>`<option value="${base}${ev?eventPath(code,ev.id):localePath(code)}" ${lang===code?'selected':''}>${name}</option>`).join('');
const latest=events[0];const status=freshness(health);const safeJSON=JSON.stringify({lang,t,health,url}).replace(/</g,'\\u003c');
return `<!doctype html><html lang="${lang}" dir="${lang==='ar'?'rtl':'ltr'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f8f9f4"><title>${e(title)}</title><meta name="description" content="${e(t.intro)}"><link rel="canonical" href="${url}">${Object.keys(names).map(l=>`<link rel="alternate" hreflang="${l}" href="${CANONICAL}${ev?eventPath(l,ev.id):localePath(l)}">`).join('')}<link rel="alternate" hreflang="x-default" href="${CANONICAL}${ev?eventPath('en',ev.id):''}"><link rel="alternate" type="application/rss+xml" title="Codex Respawn" href="${base}feed.xml"><meta property="og:type" content="website"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(t.intro)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${CANONICAL}assets/social.jpg"><meta name="twitter:card" content="summary_large_image"><link rel="icon" type="image/svg+xml" href="${base}favicon.svg"><link rel="stylesheet" href="${base}assets/style.css"><script type="module" src="${base}assets/app.mjs"></script></head><body><a class="skip" href="#main">${e(t.updates)}</a><div class="shell"><header class="site-header"><a class="brand" href="${base}${localePath(lang)}">${cursor}<span>Codex Respawn</span></a><nav aria-label="${e(t.updates)}"><a class="nav-text" href="${base}${localePath(lang)}#updates">${e(t.updates)}</a><a class="nav-text" href="${base}${localePath(lang)}#how">${e(t.how)}</a><label class="language"><span aria-hidden="true">◎</span><select aria-label="Language">${options}</select></label><a class="github" href="${REPO}" aria-label="GitHub" target="_blank" rel="noopener noreferrer"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 .6a11.7 11.7 0 0 0-3.7 22.8c.6.1.8-.2.8-.5v-2.2c-3.4.7-4.1-1.4-4.1-1.4-.5-1.3-1.3-1.6-1.3-1.6-1.1-.8.1-.8.1-.8 1.2.1 1.8 1.3 1.8 1.3 1.1 1.8 2.8 1.3 3.5 1 .1-.8.4-1.3.8-1.6-2.7-.3-5.5-1.3-5.5-6 0-1.3.5-2.4 1.3-3.2-.1-.3-.6-1.6.2-3.2 0 0 1-.3 3.3 1.2a11.6 11.6 0 0 1 6 0C17.5 5 18.5 5.3 18.5 5.3c.8 1.6.3 2.9.2 3.2.8.8 1.3 1.9 1.3 3.2 0 4.7-2.8 5.7-5.5 6 .4.4.8 1.1.8 2.2v3c0 .3.2.7.8.5A11.7 11.7 0 0 0 12 .6Z"/></svg></a></nav></header>
<main id="main">${ev?`<section class="detail"><a class="text-link" href="${base}${localePath(lang)}#updates">← ${e(t.back)}</a><p class="eyebrow">${e(t.history)}</p><h1>${e(kindLabel(ev,t))}</h1><span class="badge ${ev.state}">${e(t[ev.state])}</span><p class="source-caption">${e(t.excerpt)}</p><blockquote lang="en" dir="ltr">${e(ev.excerpt)}</blockquote><p><time datetime="${ev.publishedAt}">${e(date(ev.publishedAt,lang))}</time> · @${e(ev.author)}</p><div class="actions"><a class="button primary" href="${ev.sourceUrl}" target="_blank" rel="noopener noreferrer">${e(t.source)} ↗</a><button class="button" data-share>${e(t.share)} ↗</button></div><p class="muted">${e(t.coverage)}</p></section>`:`<section class="hero"><div class="hero-copy"><p class="eyebrow"><span></span>${e(t.tagline)}</p><h1>${lang === 'en' ? t.headline.split('\n').map(s => `<span class="headline-sentence">${e(s)}</span>`).join('') : e(t.headline).replace(/\n/g,' ')}</h1><p class="intro">${e(t.intro)}</p><div class="actions"><a class="button primary" href="${usageUrl}" target="_blank" rel="noopener noreferrer">${e(t.usage)} <span aria-hidden="true">↗</span></a><a class="button" href="#timer" data-open-timer>${e(t.remind)}</a></div></div><div class="hero-art"><img src="${base}assets/mascot.webp" width="1000" height="1000" fetchpriority="high" alt=""/><span class="orbit-label" aria-hidden="true">↻ &nbsp; RESPAWN POINT</span></div></section>
<section class="latest-strip" aria-label="${e(t.latest)}"><div class="eyebrow"><span></span>${e(t.latest)}</div>${latest?`<div class="latest-message"><strong>${e(t[latest.state])}</strong><span>${e(kindLabel(latest,t))}</span></div><a href="${latest.sourceUrl}" target="_blank" rel="noopener noreferrer">${e(t.source)} ↗</a>`:`<span>${e(t.empty)}</span>`}</section>
<div class="content-grid"><section class="updates-panel" id="updates"><div class="section-heading"><h2>${e(t.updates)}</h2><a class="feed-link" href="${base}feed.xml">RSS ↗</a></div><div class="filters" role="group" aria-label="${e(t.updates)}">${[['all','all'],['global','resets'],['banked','credits'],['usage','changes'],['signal','signals']].map(([value,key])=>`<button data-filter="${value}" aria-pressed="${value==='all'}">${e(t[key])}</button>`).join('')}</div><div class="events">${events.map(item=>row(item,lang,base)).join('')}</div><p class="empty" hidden>${e(t.empty)}</p><button class="more" hidden>${e(t.more)} <span aria-hidden="true">↓</span></button></section>
<aside class="timer-card" id="timer"><div class="timer-heading"><h2>${e(t.timerTitle)}</h2><span aria-hidden="true">↻</span></div><div class="clock" dir="ltr">--:--:--</div><p class="timer-state" aria-live="polite">${e(t.timerEmpty)}</p><p>${e(t.timerIntro)}</p><button class="button lime" data-edit-timer>${e(t.setTimer)}</button><form class="timer-form" hidden><label for="reset-time">${e(t.dateLabel)}</label><input id="reset-time" type="datetime-local" required><p class="form-error" role="alert" hidden></p><button class="button lime" type="submit">${e(t.save)}</button></form><div class="timer-tools" hidden><button data-calendar>${e(t.calendar)} ↗</button><button data-clear>${e(t.clear)}</button></div><p class="timer-note">${e(t.timerNote)}</p></aside></div>`}
<section id="how" class="faq"><div class="faq-heading"><span class="bulb" aria-hidden="true">↻</span><h2>${e(t.faqTitle)}</h2></div>${[1,2,3,4].map(n=>`<details><summary>${e(t['q'+n])}<span aria-hidden="true">+</span></summary><p>${e(t['a'+n])}${n===1||n===2?` <a href="${guide}" target="_blank" rel="noopener noreferrer">OpenAI ↗</a>`:''}</p></details>`).join('')}</section>
<section class="source-health"><div><span class="health-dot ${status}"></span><strong data-health>${e(t[status])}</strong><span>${e(t.checked)}: <time data-health-time datetime="${e(health.lastSuccessAt||'')}">${health.lastSuccessAt?e(date(health.lastSuccessAt,lang)):'—'}</time></span></div><p>${e(t.coverage)}</p><div class="data-links"><a href="${base}feed.xml">${e(t.rss)} ↗</a><a href="${base}events.json">${e(t.json)} ↗</a><a href="${REPO}/actions">GitHub Actions ↗</a></div></section></main>
<footer><div class="footer-links"><a href="https://shixilin.com/?lang=${lang}">${e(t.creator)} ↗</a><a href="https://shixilin.com/support?lang=${lang}">${e(t.support)}</a><a href="mailto:info@elevencapital.ltd">${e(t.contact)} ↗</a></div><div class="footer-note"><span>${e(t.independent)}</span><span>${e(t.privacy)}</span></div></footer></div><p class="toast" role="status" hidden></p><script id="page-data" type="application/json">${safeJSON}</script></body></html>`;
}
for(const lang of Object.keys(locales)){await write(`${localePath(lang)}index.html`,render(lang));for(const ev of events)await write(`${eventPath(lang,ev.id)}index.html`,render(lang,ev));}
const links=Object.keys(locales).flatMap(lang=>[CANONICAL+localePath(lang),...events.map(ev=>CANONICAL+eventPath(lang,ev.id))]);
await write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${links.map(url=>`<url><loc>${e(url)}</loc></url>`).join('')}</urlset>`);
await write('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${CANONICAL}sitemap.xml\n`);
await write('feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Codex Respawn</title><link>${CANONICAL}</link><description>Source-linked Codex reset announcements. Personal account status must be checked separately.</description><language>en</language>${events.map(ev=>`<item><title>${e(kindLabel(ev,locales.en))}: ${e(locales.en[ev.state])}</title><link>${CANONICAL}${eventPath('en',ev.id)}</link><guid isPermaLink="false">codex-respawn:${ev.id}</guid><pubDate>${new Date(ev.publishedAt).toUTCString()}</pubDate><description>${e(ev.excerpt+' Source: '+ev.sourceUrl)}</description></item>`).join('')}</channel></rss>`);
await write('.nojekyll','');
console.log(`Built ${Object.keys(locales).length} locales, ${events.length} events and ${links.length} pages.`);
