import {postText} from '../src/post-text.mjs';
import {visitorCopy} from '../src/visitor-copy.mjs';
import {priorityCopy,resetDefinitions,earlierPosts} from '../src/priority-details.mjs';
import { createHash } from 'node:crypto';
import { platformCopy } from '../src/platform-copy.mjs';
import { clockPanel } from '../src/clock-panel.mjs';
import { offers } from '../src/offers.mjs';
import { readFile, writeFile, mkdir, cp } from 'node:fs/promises';
import { locales, names } from '../src/locales.mjs';
import { CANONICAL, REPO, escapeHtml as e, localePath, eventPath, freshness } from '../src/shared.mjs';
import { validateEvent, postPlatform } from '../src/evidence.mjs';
const root = new URL('../', import.meta.url);
const out = new URL('dist/', root);
const platforms = JSON.parse(await readFile(new URL('data/platforms.json',root),'utf8')); 
const events = JSON.parse(await readFile(new URL('data/events.json', root), 'utf8'));
const heat = JSON.parse(await readFile(new URL('data/topic-heat.json',root),'utf8'));
const health = JSON.parse(await readFile(new URL('data/health.json', root), 'utf8'));
events.forEach(validateEvent);
let translations={posts:{}};try{translations=JSON.parse(await readFile(new URL('data/translations.json',root),'utf8'));}catch(error){if(error.code!=='ENOENT')throw error;}
for(const event of events){const entry=translations.posts[event.id];if(entry&&entry.excerpt===event.excerpt&&entry.contentHash===event.contentHash)event.localized={excerpt:entry.excerpt,contentHash:entry.contentHash,texts:entry.texts,fullText:entry.fullText,fullTexts:entry.fullTexts};}
for(const platform of Object.values(platforms))for(const key of ['latest','latestGift','lastReset'])if(platform[key])platform[key]=events.find(event=>event.id===platform[key].id)||platform[key];
await mkdir(out, { recursive: true });
await cp(new URL('public/', root), out, { recursive: true, filter: path => !String(path).endsWith('mascot-source.png') });
await mkdir(new URL('assets/', out), { recursive: true });
const clientFiles=['announcement-time.mjs','drummer.mjs','drummer-data.mjs','drummer-client.mjs','topic-heat.mjs','topic-heat-client.mjs','elapsed.mjs','locales.mjs','app.mjs','style.css','shared.mjs','reset-status.mjs','platform-copy.mjs','clock-app.mjs','clock-copy.mjs','watch-copy.mjs','live-data.mjs','offers.mjs','priority-details.mjs','post-text.mjs','visitor-copy.mjs','evidence.mjs','clocks.css'];
const assetVersion=createHash('sha256').update(Buffer.concat(await Promise.all([...clientFiles.map(file=>readFile(new URL('src/'+file,root))),readFile(new URL('public/assets/social.jpg',root)),readFile(new URL('public/assets/drummer-poster.webp',root)),readFile(new URL('public/assets/drummer-atlas.webp',root))]))).digest('hex').slice(0,10);
for (const file of clientFiles) {const source=new URL(`src/${file}`,root),target=new URL(`assets/${file}`,out);if(file.endsWith('.mjs')){const text=await readFile(source,'utf8');await writeFile(target,text.replace(/((?:from|import)\s*['"]\.\/[^'"]+\.mjs)(['"])/g,(_,path,quote)=>path+'?v='+assetVersion+quote));}else await cp(source,target);}
for (const [name,data] of Object.entries({events,health,platforms,'topic-heat':JSON.parse(await readFile(new URL('data/topic-heat.json',root),'utf8'))})) await writeFile(new URL(name+'.json',out),JSON.stringify(data,null,2)+'\n');
const write = async (path, text) => {const url = new URL(path, out); await mkdir(new URL('./',url),{recursive:true});await writeFile(url,text);};
const bookmarkNames={"en":"Codex & Claude Resets","zh":"Codex与Claude重置","zh-Hant":"Codex與Claude重置","ja":"Codex・Claudeリセット","ko":"Codex·Claude 초기화","es":"Restablecimientos de Codex y Claude","fr":"Réinitialisations Codex et Claude","de":"Codex- und Claude-Resets","ar":"إعادة ضبط Codex وClaude"};
const date = (at,lang) => new Intl.DateTimeFormat(lang, { dateStyle:'medium', timeStyle:'short', timeZone:'UTC' }).format(new Date(at)) + ' UTC';
const kindLabel = (ev,t) => t[ev.kind === 'usage' ? 'usageKind' : ev.kind];
const icon = kind => ({global:'↻',banked:'☆',usage:'↗',signal:'·'}[kind] || '↻');
const cursor = '<img class="brand-icon" src="__BASE__favicon.svg?v=4" width="42" height="42" alt="">';
function row(ev,lang,base) {const t=locales[lang];return `<article class="event-row" data-kind="${e(ev.kind)}" data-platform-feed="${postPlatform(ev.author)}"><div class="event-icon" aria-hidden="true">${icon(ev.kind)}</div><div class="event-main"><div class="event-title"><a href="${base}${eventPath(lang,ev.id)}">${e(kindLabel(ev,t))}</a><span class="badge ${ev.state}">${e(t[ev.state])}</span></div>${postText(ev,lang)}<div class="event-meta"><span>${postPlatform(ev.author)==="claude"?"Claude":"Codex"} · @${e(ev.author)}</span><time datetime="${ev.publishedAt}" title="${ev.publishedAt}">${e(date(ev.publishedAt,lang))}</time><a href="${e(ev.sourceUrl)}" target="_blank" rel="noopener noreferrer">${e(t.source)} ↗</a></div></div></article>`;}
function render(lang,ev=null){
const t={...locales[lang],a1:platformCopy[lang].accountNote,a3:platformCopy[lang].clockNote,a4:platformCopy[lang].sourceNote};const path=ev?eventPath(lang,ev.id):localePath(lang);const base=ev?(lang==='en'?'../../':'../../../'):(lang==='en'?'./':'../');const url=CANONICAL+path;const title=ev?`${kindLabel(ev,t)} · ${t[ev.state]} | Codex & Claude Resets`:bookmarkNames[lang];
const options=Object.entries(names).map(([code,name])=>`<option value="${base}${ev?eventPath(code,ev.id):localePath(code)}" ${lang===code?'selected':''}>${name}</option>`).join('');
const latest=events.find(item=>['reported','announced'].includes(item.state))||events[0];const status=freshness(health);const safeJSON=JSON.stringify({lang,t,health,url,platforms:Object.fromEntries(Object.entries(platforms).map(([id,{usageUrl,...record}])=>[id,record])),events}).replace(/</g,'\\u003c');
return `<!doctype html><html lang="${lang}" dir="${lang==='ar'?'rtl':'ltr'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f8f9f4"><title>${e(title)}</title><meta name="description" content="${e(platformCopy[lang].title)}"><link rel="canonical" href="${url}">${Object.keys(names).map(l=>`<link rel="alternate" hreflang="${l}" href="${CANONICAL}${ev?eventPath(l,ev.id):localePath(l)}">`).join('')}<link rel="alternate" hreflang="x-default" href="${CANONICAL}${ev?eventPath('en',ev.id):''}"><link rel="alternate" type="application/rss+xml" title="Codex &amp; Claude Resets" href="${base}feed.xml"><meta property="og:type" content="website"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(platformCopy[lang].title)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${CANONICAL}assets/social.jpg?v=${assetVersion}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Codex &amp; Claude Resets — reset announcements in your local time"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="${base}favicon.ico?v=4" sizes="16x16 32x32 48x48"><link rel="icon" type="image/svg+xml" href="${base}favicon.svg?v=4" sizes="any"><link rel="icon" sizes="32x32" href="${base}favicon-32.png?v=4"><link rel="apple-touch-icon" href="${base}apple-touch-icon.png?v=4"><link rel="stylesheet" href="${base}assets/style.css?v=${assetVersion}"><link rel="stylesheet" href="${base}assets/clocks.css?v=${assetVersion}"><script type="module" src="${base}assets/app.mjs?v=${assetVersion}"></script><script type="module" src="${base}assets/clock-app.mjs?v=${assetVersion}"></script></head><body><a class="skip" href="#main">${e(t.updates)}</a><div class="shell"><header class="site-header"><a class="brand" href="${base}${localePath(lang)}">${cursor.replace("__BASE__",base)}<span>Codex &amp; Claude Resets</span></a><nav aria-label="${e(t.updates)}"><a class="nav-text" href="${base}${localePath(lang)}#updates">${e(t.updates)}</a><label class="language"><span aria-hidden="true">◎</span><select aria-label="Language">${options}</select></label><a class="github" href="${REPO}" aria-label="GitHub" target="_blank" rel="noopener noreferrer"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 .6a11.7 11.7 0 0 0-3.7 22.8c.6.1.8-.2.8-.5v-2.2c-3.4.7-4.1-1.4-4.1-1.4-.5-1.3-1.3-1.6-1.3-1.6-1.1-.8.1-.8.1-.8 1.2.1 1.8 1.3 1.8 1.3 1.1 1.8 2.8 1.3 3.5 1 .1-.8.4-1.3.8-1.6-2.7-.3-5.5-1.3-5.5-6 0-1.3.5-2.4 1.3-3.2-.1-.3-.6-1.6.2-3.2 0 0 1-.3 3.3 1.2a11.6 11.6 0 0 1 6 0C17.5 5 18.5 5.3 18.5 5.3c.8 1.6.3 2.9.2 3.2.8.8 1.3 1.9 1.3 3.2 0 4.7-2.8 5.7-5.5 6 .4.4.8 1.1.8 2.2v3c0 .3.2.7.8.5A11.7 11.7 0 0 0 12 .6Z"/></svg></a></nav></header>
<main id="main">${ev?`<section class="detail"><a class="text-link" href="${base}${localePath(lang)}#updates">← ${e(t.back)}</a><p class="eyebrow">${e(t.history.replace(/Codex/g,postPlatform(ev?.author||"thsottiaux")==="claude"?"Claude":"Codex"))}</p><h1>${e(kindLabel(ev,t))}</h1><span class="badge ${ev.state}">${e(t[ev.state])}</span><p class="source-caption">${e(t.excerpt)}</p>${postText(ev,lang,'detail-excerpt','blockquote')}<p><time datetime="${ev.publishedAt}">${e(date(ev.publishedAt,lang))}</time> · @${e(ev.author)}</p><div class="actions"><a class="button primary" href="${ev.sourceUrl}" target="_blank" rel="noopener noreferrer">${e(t.source)} ↗</a><button class="button" data-share>${e(t.share)} ↗</button></div><p class="muted">${e(t.coverage)}</p></section>`:`${clockPanel(platforms,lang,base,assetVersion,events,heat)}
<details class="supplemental" open><summary>${e(platformCopy[lang].gifts)} <span class="disclosure-chevron" aria-hidden="true"></span></summary>${offers(platforms,lang)}</details>
<details class="tweet-archive" id="updates" open><summary>${e(priorityCopy[lang].archive)} <span class="disclosure-chevron" aria-hidden="true"></span></summary><div class="content-grid"><section class="updates-panel"><div class="filters platform-filters" role="group" aria-label="Platform"><button data-platform-filter="all" aria-pressed="true">${e(t.all)}</button><button data-platform-filter="codex" aria-pressed="false">Codex</button><button data-platform-filter="claude" aria-pressed="false">Claude</button></div><div class="events">${earlierPosts(events).map(item=>row(item,lang,base)).join('')}</div><p class="empty" hidden>${e(t.empty)}</p><button class="more" hidden>${e(t.more)} <span aria-hidden="true">↓</span></button></section>
</div></details>`}
<section class="source-health"><div class="check-time"><span>${e(visitorCopy[lang].checked)}</span><time data-health-time datetime="${e(health.lastSuccessAt||'')}">${health.lastSuccessAt?e(date(health.lastSuccessAt,lang)):'—'}</time></div><p class="check-warning" data-health hidden></p></section></main>
<footer><div class="footer-links"><a href="https://shixilin.com/?lang=${lang}">${e(t.creator)} ↗</a><a href="https://shixilin.com/support?lang=${lang}">${e(t.support)}</a><a href="mailto:info@elevencapital.ltd">${e(t.contact)} ↗</a></div></footer></div><p class="toast" role="status" hidden></p><script id="page-data" type="application/json">${safeJSON}</script></body></html>`;
}
for(const lang of Object.keys(locales)){await write(`${localePath(lang)}index.html`,render(lang));for(const ev of events)await write(`${eventPath(lang,ev.id)}index.html`,render(lang,ev));}
const links=Object.keys(locales).flatMap(lang=>[CANONICAL+localePath(lang),...events.map(ev=>CANONICAL+eventPath(lang,ev.id))]);
await write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${links.map(url=>`<url><loc>${e(url)}</loc></url>`).join('')}</urlset>`);
await write('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${CANONICAL}sitemap.xml\n`);
await write('feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Codex &amp; Claude Resets</title><link>${CANONICAL}</link><description>Source-linked Codex and Claude reset announcements. Personal account status must be checked separately.</description><language>en</language>${events.map(ev=>`<item><title>${e(kindLabel(ev,locales.en))}: ${e(locales.en[ev.state])}</title><link>${CANONICAL}${eventPath('en',ev.id)}</link><guid isPermaLink="false">codex-respawn:${ev.id}</guid><pubDate>${new Date(ev.publishedAt).toUTCString()}</pubDate><description>${e(ev.excerpt+' Source: '+ev.sourceUrl)}</description></item>`).join('')}</channel></rss>`);
await write('.nojekyll','');
console.log(`Built ${Object.keys(locales).length} locales, ${events.length} events and ${links.length} pages.`);
