import { freshness, calendarFile } from './shared.mjs';
const {lang,t,health,url} = JSON.parse(document.querySelector('#page-data').textContent);
document.querySelector('.language select').addEventListener('change',e=>location.assign(e.target.value));
document.querySelectorAll('time[datetime]').forEach(el=>{const at=Date.parse(el.dateTime);if(Number.isFinite(at))el.textContent=new Intl.DateTimeFormat(lang,{dateStyle:'medium',timeStyle:'short'}).format(at);});
const showHealth=()=>{const state=freshness(health);document.querySelector('[data-health]').textContent=t[state];document.querySelector('.health-dot').className=`health-dot ${state}`;};showHealth();setInterval(showHealth,60000);
const rows=[...document.querySelectorAll('.event-row')];let active='all',limit=5;
const filter=()=>{const matches=rows.filter(el=>active==='all'||el.dataset.kind===active);rows.forEach(el=>el.hidden=!matches.slice(0,limit).includes(el));const more=document.querySelector('.more');if(more)more.hidden=matches.length<=limit;const empty=document.querySelector('.empty');if(empty)empty.hidden=matches.length>0;};
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{active=button.dataset.filter;limit=5;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));filter();}));document.querySelector('.more')?.addEventListener('click',()=>{limit+=5;filter();});filter();
const key='codex-respawn-timer-v1';let timestamp=0;try{timestamp=Number(localStorage.getItem(key))||0;}catch{}
const clock=document.querySelector('.clock'),form=document.querySelector('.timer-form'),input=document.querySelector('#reset-time'),edit=document.querySelector('[data-edit-timer]');
const tick=()=>{if(!clock)return;const remain=Math.max(0,timestamp-Date.now());const secs=Math.ceil(remain/1000);clock.textContent=timestamp?`${String(Math.floor(secs/3600)).padStart(2,'0')}:${String(Math.floor(secs/60)%60).padStart(2,'0')}:${String(secs%60).padStart(2,'0')}`:'--:--:--';document.querySelector('.timer-state').textContent=timestamp?(remain>0?new Intl.DateTimeFormat(lang,{dateStyle:'medium',timeStyle:'short'}).format(timestamp):t.timerDue):t.timerEmpty;document.querySelector('.timer-tools').hidden=!timestamp;};tick();if(clock)setInterval(tick,1000);
const openTimer=()=>{if(!form)return;form.hidden=false;edit.hidden=true;input.focus({preventScroll:true});};edit?.addEventListener('click',openTimer);document.querySelector('[data-open-timer]')?.addEventListener('click',openTimer);
form?.addEventListener('submit',e=>{e.preventDefault();const value=new Date(input.value).getTime();const error=document.querySelector('.form-error');if(!Number.isFinite(value)||value<=Date.now()||value>Date.now()+366*86400000){error.textContent=t.invalid;error.hidden=false;return;}timestamp=value;try{localStorage.setItem(key,String(timestamp));}catch{}error.hidden=true;form.hidden=true;edit.hidden=false;tick();});
document.querySelector('[data-clear]')?.addEventListener('click',()=>{timestamp=0;try{localStorage.removeItem(key);}catch{}tick();});
document.querySelector('[data-calendar]')?.addEventListener('click',()=>{if(!timestamp)return;const blob=new Blob([calendarFile(timestamp,t.timerDue)],{type:'text/calendar;charset=utf-8'});const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download='codex-respawn.ics';a.click();setTimeout(()=>URL.revokeObjectURL(href),1000);});
document.querySelector('[data-share]')?.addEventListener('click',async()=>{try{if(navigator.share)await navigator.share({title:document.title,url});else{await navigator.clipboard.writeText(url);const toast=document.querySelector('.toast');toast.textContent=t.copied;toast.hidden=false;setTimeout(()=>toast.hidden=true,2500);}}catch{}});
