const keys=['public','personal','set','label','save','cancel','clear','calendar','alarm','armed','alarmNote','empty','due','invalid','hours','minutes','seconds','localNow','nextAt','publicNote','personalNote','stop','soundBlocked'];
const rows={
en:['Public reset','My timer','Set my reset time','Reset time shown in your account','Save timer','Cancel','Clear timer','Add to calendar','Enable alarm','Alarm enabled','Keep this page open and sound on. For reminders after closing it, add to your calendar.','Enter the reset time shown in your account.','Your timer is due. Check your account.','Choose a future time within the next year.','HOURS','MINUTES','SECONDS','Your local time','Reset at','Tracks announced public resets. Your account may have a different cycle.','Saved only in this browser. Enter your account’s reset time; this site cannot read your quota.','Dismiss','Sound unavailable. Use a calendar reminder.'],
zh:['公开重置','我的计时器','设置重置时间','账号页面显示的重置时间','保存计时器','取消','清除计时器','添加到日历','开启闹钟','闹钟已开启','请保持网页打开并允许播放声音。关闭网页后的提醒，请添加到系统日历。','填入账号页面显示的重置时间。','计时已到，请查看账号额度。','请选择未来一年内的时间。','小时','分钟','秒','你的当地时间','重置时刻','追踪已公布的公开重置；你的账号可能采用不同周期。','仅保存在本浏览器。请填入账号的重置时间，本站无法读取你的额度。','关闭提醒','暂时无法播放声音，请使用日历提醒。'],
'zh-Hant':['公開重置','我的計時器','設定重置時間','帳號頁面顯示的重置時間','儲存計時器','取消','清除計時器','加入行事曆','開啟鬧鐘','鬧鐘已開啟','請保持網頁開啟並允許播放聲音。關閉網頁後的提醒，請加入系統行事曆。','填入帳號頁面顯示的重置時間。','計時已到，請查看帳號額度。','請選擇未來一年內的時間。','小時','分鐘','秒','你的當地時間','重置時刻','追蹤已公布的公開重置；你的帳號可能採用不同週期。','僅儲存在本瀏覽器。請填入帳號的重置時間，本站無法讀取你的額度。','關閉提醒','暫時無法播放聲音，請使用行事曆提醒。'],
ja:['一斉リセット','自分のタイマー','リセット時刻を設定','アカウントに表示されるリセット時刻','保存','キャンセル','タイマーを削除','カレンダーに追加','アラームを有効にする','アラーム有効','このページを開いたまま音声を許可してください。閉じた後の通知はカレンダーをご利用ください。','アカウントに表示されるリセット時刻を入力してください。','設定時刻になりました。アカウントをご確認ください。','今から1年以内の未来の時刻を選択してください。','時間','分','秒','現地時刻','リセット時刻','発表済みの一斉リセットを追跡します。個人の周期は異なる場合があります。','このブラウザーにのみ保存。利用枠の情報は読み取りません。','通知を閉じる','音声を再生できません。カレンダーをご利用ください。'],
ko:['일괄 초기화','내 타이머','초기화 시간 설정','계정에 표시된 초기화 시간','저장','취소','타이머 삭제','캘린더에 추가','알람 켜기','알람 켜짐','페이지를 열어 두고 소리를 허용하세요. 페이지를 닫은 후에는 캘린더 알림을 이용하세요.','계정에 표시된 초기화 시간을 입력하세요.','설정 시간이 되었습니다. 계정을 확인하세요.','앞으로 1년 이내의 시간을 선택하세요.','시간','분','초','현지 시간','초기화 시간','공개된 일괄 초기화를 추적합니다. 개인 계정 주기는 다를 수 있습니다.','이 브라우저에만 저장됩니다. 이 사이트는 계정 사용량을 읽지 않습니다.','알림 닫기','소리를 재생할 수 없습니다. 캘린더 알림을 이용하세요.'],
es:['Restablecimiento general','Mi temporizador','Fijar mi hora','Hora de restablecimiento indicada en tu cuenta','Guardar','Cancelar','Borrar temporizador','Añadir al calendario','Activar alarma','Alarma activada','Mantén esta página abierta y permite el sonido. Para avisos con la página cerrada, usa el calendario.','Introduce la hora que aparece en tu cuenta.','Ha llegado la hora. Consulta tu cuenta.','Elige una hora futura dentro del próximo año.','HORAS','MINUTOS','SEGUNDOS','Tu hora local','Se restablece a las','Sigue los restablecimientos generales anunciados. El ciclo de tu cuenta puede ser distinto.','Se guarda solo en este navegador. Este sitio no puede leer tu cuota.','Cerrar aviso','Sonido no disponible. Usa un aviso del calendario.'],
fr:['Réinitialisation générale','Mon minuteur','Définir mon heure','Heure de réinitialisation affichée dans votre compte','Enregistrer','Annuler','Effacer le minuteur','Ajouter au calendrier','Activer l’alarme','Alarme activée','Gardez cette page ouverte et autorisez le son. Pour un rappel après fermeture, utilisez le calendrier.','Saisissez l’heure affichée dans votre compte.','L’heure est arrivée. Consultez votre compte.','Choisissez une heure future dans les douze prochains mois.','HEURES','MINUTES','SECONDES','Votre heure locale','Réinitialisation à','Suit les réinitialisations générales annoncées. Le cycle de votre compte peut être différent.','Enregistré uniquement dans ce navigateur. Ce site ne peut pas lire votre quota.','Fermer le rappel','Son indisponible. Utilisez un rappel du calendrier.'],
de:['Allgemeiner Reset','Mein Timer','Reset-Zeit festlegen','Im Konto angezeigte Reset-Zeit','Speichern','Abbrechen','Timer löschen','Zum Kalender hinzufügen','Alarm aktivieren','Alarm aktiviert','Diese Seite geöffnet lassen und Ton erlauben. Für Erinnerungen nach dem Schließen den Kalender verwenden.','Gib die in deinem Konto angezeigte Reset-Zeit ein.','Die Zeit ist erreicht. Prüfe dein Konto.','Wähle einen zukünftigen Zeitpunkt innerhalb eines Jahres.','STUNDEN','MINUTEN','SEKUNDEN','Deine Ortszeit','Reset um','Zeigt angekündigte allgemeine Resets. Dein Konto kann einen anderen Zyklus haben.','Nur in diesem Browser gespeichert. Diese Website kann dein Kontingent nicht lesen.','Hinweis schließen','Ton nicht verfügbar. Nutze eine Kalendererinnerung.'],
ar:['إعادة الضبط العامة','مؤقّتي','تحديد موعدي','موعد إعادة الضبط المعروض في حسابك','حفظ','إلغاء','مسح المؤقّت','إضافة إلى التقويم','تفعيل المنبّه','المنبّه مفعّل','أبقِ الصفحة مفتوحة واسمح بالصوت. للتذكير بعد إغلاقها، استخدم التقويم.','أدخل الموعد المعروض في حسابك.','حان الموعد المحدّد. تحقّق من حسابك.','اختر موعدًا مستقبليًا خلال السنة القادمة.','ساعات','دقائق','ثوانٍ','توقيتك المحلي','موعد إعادة الضبط','يتابع مواعيد إعادة الضبط العامة المعلنة. قد تختلف دورة حسابك.','يُحفظ في هذا المتصفّح فقط. لا يستطيع الموقع قراءة حصّتك.','إغلاق التنبيه','الصوت غير متاح. استخدم تذكير التقويم.']
};
export const clockCopy=Object.fromEntries(Object.entries(rows).map(([lang,row])=>[lang,Object.fromEntries(keys.map((key,i)=>[key,row[i]]))]));

const soundFallback={"en":"Sound unavailable. On-page alerts remain active.","zh":"暂时无法播放声音，页面内提醒仍然有效。","zh-Hant":"暫時無法播放聲音，頁面內提醒仍然有效。","ja":"音声を再生できません。ページ内の通知は有効です。","ko":"소리를 재생할 수 없습니다. 페이지 내 알림은 계속 표시됩니다.","es":"Sonido no disponible. Las alertas en la página siguen activas.","fr":"Son indisponible. Les alertes sur la page restent actives.","de":"Ton nicht verfügbar. Hinweise auf der Seite bleiben aktiv.","ar":"الصوت غير متاح. تظل التنبيهات داخل الصفحة مفعّلة."};
for(const [lang,text]of Object.entries(soundFallback))clockCopy[lang].soundBlocked=text;
