export const names = { en: 'English', zh: '简体中文', 'zh-Hant': '繁體中文', ja: '日本語', ko: '한국어', es: 'Español', fr: 'Français', de: 'Deutsch', ar: 'العربية' };
const keys = ['tagline','headline','intro','usage','remind','updates','how','latest','source','all','resets','credits','changes','signals','global','banked','usageKind','signal','reported','announced','information','unconfirmed','timerTitle','timerIntro','setTimer','dateLabel','save','clear','calendar','timerEmpty','timerDue','timerNote','fresh','stale','degraded','checked','empty','more','share','copied','creator','support','contact','independent','faqTitle','q1','a1','q2','a2','q3','a3','q4','a4','coverage','excerpt','back','history','rss','json','privacy','invalid','shareTitle'];
const rows = {
en: [
'A checkpoint for your next idea', 'Out of tokens.\nNot out of ideas.', 'Follow Codex reset announcements. Save your own reset time. Get back to building.', 'Check my usage', 'Set a reminder', 'Updates', 'How resets work', 'LATEST SIGNAL', 'Read source', 'All', 'Resets', 'Reset credits', 'Usage', 'Unconfirmed', 'Quota reset', 'Reset credit', 'Usage update', 'Reset signal', 'Reported complete', 'Announced', 'Information', 'Unconfirmed', 'Your next session', 'Add the reset time shown in your Codex account.', 'Set my timer', 'Your reset date and time', 'Save timer', 'Clear timer', 'Add to calendar', 'Your next idea can wait here.', 'Time to check your account', 'Saved on this device. Your account is the authority; this timer cannot verify a reset.', 'Sources checked', 'Updates may be out of date', 'Some sources are unavailable', 'Last successful check', 'No updates in this category.', 'Show more updates', 'Share', 'Link copied', 'Made by Shixi Lin', 'Support this project', 'Work together', 'Independent, open-source project. Not affiliated with OpenAI.', 'A reset. A reset credit. Two different things.', 'Does a public reset apply to me?', 'Eligibility depends on the announcement and your plan. Check your Codex usage dashboard or run /status in the CLI. A post about a reset does not verify your personal balance.', 'What is a reset credit?', 'A banked reset is a saved reset that eligible accounts can redeem later. Availability and what it restores depend on the current offer. Follow the instructions in your account.', 'Can this site predict the next reset?', 'No. Public announcements, personal usage windows and redeemable credits are different. The timer uses the time you enter; it never predicts an OpenAI announcement.', 'Where do the updates come from?', 'Public posts by OpenAI and its Codex lead. Candidate links are discovered through a community feed, then checked against X’s official embed endpoint. Incomplete or ambiguous text stays unconfirmed. Scheduled checks can be delayed.', 'Coverage: selected public announcements; not a complete account or service-status feed.', 'Source excerpt · original language', 'Back to updates', 'Codex reset history', 'RSS feed', 'JSON feed', 'No login. Timer stays in your browser. Calendar downloads stay on your device.', 'Choose a valid future date and time.', 'Codex reset updates and personal timer'
],
zh: [
'给下一个灵感留个复活点', '额度用完了，灵感还在。', '追踪Codex重置公告，记下自己账号的恢复时间，接着把想法做出来。', '查看我的额度', '设置提醒', '最新消息', '重置说明', '最新线索', '查看来源', '全部', '额度重置', '重置次数', '额度变化', '尚未确认', '额度重置', '重置卡', '额度更新', '重置线索', '已宣布完成', '已预告', '信息', '尚未确认', '下一次，接着做', '填入Codex账号中显示的恢复时间。', '设置我的计时器', '恢复日期与时间', '保存计时器', '清除计时器', '添加到日历', '下一个想法，先在这里等你。', '到时间了，去检查账号吧', '仅保存在本机。实际额度以账号为准，计时器无法核实重置是否完成。', '来源已检查', '消息可能已经过期', '部分来源暂时不可用', '上次成功检查', '这个分类暂时没有消息。', '查看更多消息', '分享', '链接已复制', '林拾汐制作', '支持这个项目', '合作联系', '独立开源项目，与OpenAI无隶属关系。', '额度重置与重置卡，是两回事。', '公开重置适用于我吗？', '适用范围取决于公告和账号方案。请查看Codex额度面板，或在CLI运行/status。公开帖子不能核实你个人账号的余额。', '什么是重置卡？', '它是符合条件的账号可以留到以后使用的重置机会。是否提供、恢复哪些额度，取决于当前活动，请以账号中的说明为准。', '这里能预测下次重置吗？', '不能。公开公告、个人额度窗口和重置卡各不相同。计时器使用你自己填入的时间，不预测OpenAI何时发布公告。', '消息从哪里来？', '来自OpenAI及Codex负责人公开发布的帖子。社区信息源只提供候选链接，随后通过X官方嵌入接口核对。原文不完整或含义不明确时，保留为尚未确认；定时检查也可能延迟。', '覆盖部分公开公告，不是完整的个人额度或服务状态记录。', '来源摘录 · 保留原文语言', '返回消息列表', 'Codex重置记录', 'RSS订阅', 'JSON数据', '无需登录。计时器保存在浏览器中，下载的日历文件留在本机。', '请选择有效的未来日期与时间。', 'Codex重置消息与个人计时器'
],
'zh-Hant': [
'替下一個靈感留個復活點', '額度用完了，靈感還在。', '追蹤Codex重置公告，記下自己帳號的恢復時間，接著把想法做出來。', '查看我的額度', '設定提醒', '最新消息', '重置說明', '最新線索', '查看來源', '全部', '額度重置', '重置次數', '額度變化', '尚未確認', '額度重置', '重置卡', '額度更新', '重置線索', '已宣布完成', '已預告', '資訊', '尚未確認', '下一次，接著做', '填入Codex帳號中顯示的恢復時間。', '設定我的計時器', '恢復日期與時間', '儲存計時器', '清除計時器', '加入行事曆', '下一個想法，先在這裡等你。', '時間到了，去檢查帳號吧', '僅儲存在本機。實際額度以帳號為準，計時器無法核實重置是否完成。', '來源已檢查', '消息可能已經過期', '部分來源暫時無法使用', '上次成功檢查', '這個分類暫時沒有消息。', '查看更多消息', '分享', '連結已複製', '林拾汐製作', '支持這個專案', '合作聯絡', '獨立開源專案，與OpenAI無隸屬關係。', '額度重置與重置卡，是兩回事。', '公開重置適用於我嗎？', '適用範圍取決於公告和帳號方案。請查看Codex額度面板，或在CLI執行/status。公開貼文無法核實你個人帳號的餘額。', '什麼是重置卡？', '它是符合條件的帳號可以留到以後使用的重置機會。是否提供、恢復哪些額度，取決於目前活動，請以帳號中的說明為準。', '這裡能預測下次重置嗎？', '不能。公開公告、個人額度週期和重置卡各不相同。計時器使用你自己填入的時間，不預測OpenAI何時發布公告。', '消息從哪裡來？', '來自OpenAI及Codex負責人公開發布的貼文。社群資訊來源只提供候選連結，隨後透過X官方嵌入介面核對。原文不完整或含義不明確時，保留為尚未確認；定時檢查也可能延遲。', '涵蓋部分公開公告，並非完整的個人額度或服務狀態紀錄。', '來源摘錄 · 保留原文語言', '返回消息列表', 'Codex重置紀錄', 'RSS訂閱', 'JSON資料', '無需登入。計時器儲存在瀏覽器中，下載的行事曆檔案留在本機。', '請選擇有效的未來日期與時間。', 'Codex重置消息與個人計時器'
],
ja: [
'次のアイデアのためのチェックポイント', '利用枠は尽きても、\nアイデアは尽きない。', 'Codexのリセット告知を確認し、自分の利用枠が回復する時刻を保存。制作の続きを始めよう。', '利用状況を確認', 'リマインダーを設定', '更新情報', 'リセットについて', '最新の情報', '情報源を見る', 'すべて', '利用枠のリセット', 'リセット権', '利用枠', '未確認', '利用枠のリセット', 'リセット権', '利用枠の更新', 'リセット関連情報', '完了の発表あり', '予告', 'お知らせ', '未確認', '次の作業に向けて', 'Codexのアカウントに表示された回復時刻を入力してください。', 'タイマーを設定', '回復する日時', 'タイマーを保存', 'タイマーを解除', 'カレンダーに追加', '次のアイデアは、ここで待っています。', 'アカウントを確認する時間です', 'この端末に保存されます。実際の利用枠はアカウントで確認してください。タイマーはリセットの完了を確認できません。', '情報源を確認済み', '情報が古くなっている可能性があります', '一部の情報源に接続できません', '最終確認成功日時', 'このカテゴリには情報がありません。', 'もっと見る', '共有', 'リンクをコピーしました', 'Shixi Linが制作', 'このプロジェクトを支援', 'お問い合わせ', '独立したオープンソースプロジェクトです。OpenAIとは提携していません。', '利用枠のリセットとリセット権は別のものです。', '公開されたリセットは自分にも適用されますか？', '対象は告知内容と契約プランによって異なります。Codexの利用状況画面、またはCLIの/statusで確認してください。公開投稿では個人の残量を確認できません。', 'リセット権とは何ですか？', '対象アカウントが後から利用できる、保存されたリセットの権利です。提供の有無や回復する利用枠は現在の条件によります。アカウント内の案内をご確認ください。', '次のリセットを予測できますか？', 'できません。公開告知、個人の利用枠の周期、リセット権はそれぞれ別です。タイマーは入力した日時を使い、OpenAIの発表を予測しません。', '情報はどこから取得していますか？', 'OpenAIとCodex責任者の公開投稿です。コミュニティのフィードから候補リンクを見つけ、Xの公式埋め込みAPIで確認します。不完全・曖昧な文面は未確認のまま扱います。定期確認は遅れる場合があります。', '一部の公開告知を掲載しています。個人の利用枠やサービス稼働状況を網羅するものではありません。', '情報源の抜粋 · 原文', '更新情報に戻る', 'Codexリセット履歴', 'RSSフィード', 'JSONフィード', 'ログイン不要。タイマーはブラウザー内に保存され、カレンダーは端末にダウンロードされます。', '有効な未来の日時を選択してください。', 'Codexリセット情報と個人用タイマー'
],
ko: [
'다음 아이디어를 위한 체크포인트', '한도는 다 써도,\n아이디어는 계속.', 'Codex 초기화 공지를 확인하고 내 계정의 한도 회복 시간을 저장하세요. 다시 만들기 시작할 시간입니다.', '내 사용량 확인', '알림 설정', '업데이트', '초기화 안내', '최신 소식', '출처 보기', '전체', '한도 초기화', '초기화 이용권', '사용 한도', '미확인', '한도 초기화', '초기화 이용권', '한도 변경', '초기화 관련 소식', '완료 발표', '예고', '안내', '미확인', '다음 작업을 위해', 'Codex 계정에 표시된 한도 회복 시간을 입력하세요.', '내 타이머 설정', '회복 날짜와 시간', '타이머 저장', '타이머 삭제', '캘린더에 추가', '다음 아이디어가 여기서 기다립니다.', '계정을 확인할 시간입니다', '이 기기에 저장됩니다. 실제 한도는 계정에서 확인하세요. 타이머는 초기화 완료 여부를 확인할 수 없습니다.', '출처 확인됨', '정보가 오래되었을 수 있습니다', '일부 출처에 연결할 수 없습니다', '마지막 확인 성공', '이 분류에는 소식이 없습니다.', '소식 더 보기', '공유', '링크 복사됨', 'Shixi Lin 제작', '프로젝트 후원', '협업 문의', '독립 오픈소스 프로젝트이며 OpenAI와 제휴하지 않습니다.', '한도 초기화와 초기화 이용권은 다릅니다.', '공개 초기화가 내 계정에도 적용되나요?', '대상은 공지와 요금제에 따라 다릅니다. Codex 사용량 화면이나 CLI의 /status로 확인하세요. 공개 게시물로 개인 계정의 잔여량을 확인할 수는 없습니다.', '초기화 이용권은 무엇인가요?', '대상 계정이 나중에 사용할 수 있도록 저장된 초기화 기회입니다. 제공 여부와 회복되는 한도는 현재 조건에 따라 다릅니다. 계정 내 안내를 확인하세요.', '다음 초기화를 예측할 수 있나요?', '아니요. 공개 공지, 개인 사용량 주기, 초기화 이용권은 서로 다릅니다. 타이머는 입력한 시간을 사용하며 OpenAI 발표를 예측하지 않습니다.', '소식은 어디서 가져오나요?', 'OpenAI와 Codex 책임자의 공개 게시물을 사용합니다. 커뮤니티 피드에서 후보 링크를 찾은 뒤 X 공식 임베드 API로 확인합니다. 불완전하거나 모호한 문구는 미확인으로 유지합니다. 예약 확인은 지연될 수 있습니다.', '일부 공개 공지만 다루며 개인 한도나 서비스 상태를 모두 기록하지는 않습니다.', '출처 발췌 · 원문', '소식으로 돌아가기', 'Codex 초기화 기록', 'RSS 피드', 'JSON 피드', '로그인이 필요 없습니다. 타이머는 브라우저에, 다운로드한 캘린더는 기기에 저장됩니다.', '유효한 미래 날짜와 시간을 선택하세요.', 'Codex 초기화 소식과 개인 타이머'
],
es: [
'Un punto de control para tu próxima idea', 'Sin cuota.\nCon ideas de sobra.', 'Sigue los anuncios de restablecimiento de Codex. Guarda tu hora de recuperación y vuelve a crear.', 'Ver mi uso', 'Crear un recordatorio', 'Novedades', 'Cómo funciona', 'ÚLTIMA SEÑAL', 'Ver fuente', 'Todo', 'Restablecimientos', 'Créditos', 'Uso', 'Sin confirmar', 'Restablecimiento de cuota', 'Crédito de restablecimiento', 'Cambio de uso', 'Señal de restablecimiento', 'Finalización anunciada', 'Anunciado', 'Información', 'Sin confirmar', 'Tu próxima sesión', 'Introduce la hora de recuperación que aparece en tu cuenta de Codex.', 'Configurar temporizador', 'Fecha y hora de recuperación', 'Guardar', 'Borrar temporizador', 'Añadir al calendario', 'Tu próxima idea te espera aquí.', 'Es hora de consultar tu cuenta', 'Se guarda en este dispositivo. Tu cuenta es la referencia; el temporizador no verifica restablecimientos.', 'Fuentes comprobadas', 'La información puede estar desactualizada', 'Algunas fuentes no están disponibles', 'Última comprobación correcta', 'No hay novedades en esta categoría.', 'Ver más novedades', 'Compartir', 'Enlace copiado', 'Creado por Shixi Lin', 'Apoyar el proyecto', 'Colaboraciones', 'Proyecto independiente de código abierto. Sin afiliación con OpenAI.', 'Restablecer la cuota y canjear un crédito son cosas distintas.', '¿Se aplica a mi cuenta un restablecimiento público?', 'Depende del anuncio y de tu plan. Consulta el panel de uso de Codex o ejecuta /status en la CLI. Una publicación no confirma tu saldo personal.', '¿Qué es un crédito de restablecimiento?', 'Es un restablecimiento guardado que las cuentas elegibles pueden canjear más adelante. Su disponibilidad y alcance dependen de la oferta vigente. Sigue las indicaciones de tu cuenta.', '¿Se puede predecir el próximo restablecimiento?', 'No. Los anuncios públicos, los periodos de uso personales y los créditos son distintos. El temporizador usa la hora que introduces; no predice anuncios de OpenAI.', '¿De dónde salen las novedades?', 'De publicaciones de OpenAI y del responsable de Codex. Un feed comunitario permite descubrir enlaces, que se verifican con el servicio oficial de inserción de X. Los textos incompletos o ambiguos quedan sin confirmar. Las comprobaciones programadas pueden retrasarse.', 'Cobertura: anuncios públicos seleccionados; no es un registro completo de cuentas ni del estado del servicio.', 'Extracto de la fuente · idioma original', 'Volver a las novedades', 'Historial de restablecimientos de Codex', 'Feed RSS', 'Feed JSON', 'Sin inicio de sesión. El temporizador se guarda en el navegador y el calendario se descarga en tu dispositivo.', 'Elige una fecha y hora futuras válidas.', 'Novedades de restablecimiento de Codex y temporizador personal'
],
fr: [
'Un point de reprise pour votre prochaine idée', 'Plus de quota.\nToujours des idées.', 'Suivez les annonces de réinitialisation de Codex. Enregistrez votre heure de renouvellement, puis reprenez vos projets.', 'Voir mon utilisation', 'Créer un rappel', 'Actualités', 'Comprendre les resets', 'DERNIER SIGNAL', 'Voir la source', 'Tout', 'Réinitialisations', 'Crédits', 'Utilisation', 'Non confirmé', 'Réinitialisation du quota', 'Crédit de réinitialisation', 'Évolution des quotas', 'Signal de réinitialisation', 'Fin annoncée', 'Annoncé', 'Information', 'Non confirmé', 'Votre prochaine session', 'Saisissez l’heure de renouvellement indiquée dans votre compte Codex.', 'Régler mon minuteur', 'Date et heure de renouvellement', 'Enregistrer', 'Effacer le minuteur', 'Ajouter au calendrier', 'Votre prochaine idée vous attend ici.', 'Il est temps de consulter votre compte', 'Enregistré sur cet appareil. Votre compte fait foi ; le minuteur ne vérifie pas les réinitialisations.', 'Sources vérifiées', 'Les informations peuvent être anciennes', 'Certaines sources sont indisponibles', 'Dernière vérification réussie', 'Aucune actualité dans cette catégorie.', 'Voir plus d’actualités', 'Partager', 'Lien copié', 'Créé par Shixi Lin', 'Soutenir le projet', 'Collaborations', 'Projet indépendant et open source. Sans affiliation avec OpenAI.', 'Réinitialisation et crédit de réinitialisation : deux choses distinctes.', 'Une réinitialisation publique s’applique-t-elle à mon compte ?', 'Cela dépend de l’annonce et de votre offre. Consultez le tableau d’utilisation de Codex ou lancez /status dans la CLI. Une publication ne confirme pas votre solde personnel.', 'Qu’est-ce qu’un crédit de réinitialisation ?', 'C’est une réinitialisation conservée pour être utilisée plus tard par les comptes éligibles. Sa disponibilité et sa portée dépendent de l’offre en cours. Suivez les instructions de votre compte.', 'Peut-on prévoir la prochaine réinitialisation ?', 'Non. Les annonces publiques, les périodes d’utilisation individuelles et les crédits sont distincts. Le minuteur utilise l’heure saisie ; il ne prédit aucune annonce d’OpenAI.', 'D’où viennent les actualités ?', 'Des publications d’OpenAI et du responsable de Codex. Un flux communautaire fournit des liens candidats, vérifiés avec le service officiel d’intégration de X. Tout texte incomplet ou ambigu reste non confirmé. Les vérifications programmées peuvent être retardées.', 'Couverture : une sélection d’annonces publiques, pas un relevé complet des comptes ou de l’état du service.', 'Extrait de la source · langue originale', 'Retour aux actualités', 'Historique des réinitialisations de Codex', 'Flux RSS', 'Flux JSON', 'Sans connexion. Le minuteur reste dans votre navigateur et le calendrier est téléchargé sur votre appareil.', 'Choisissez une date et une heure futures valides.', 'Actualités des réinitialisations Codex et minuteur personnel'
],
de: [
'Ein Speicherpunkt für deine nächste Idee', 'Kontingent leer.\nKopf voller Ideen.', 'Verfolge Codex-Reset-Ankündigungen. Speichere deine eigene Rücksetzzeit und arbeite an deinen Ideen weiter.', 'Meine Nutzung prüfen', 'Erinnerung erstellen', 'Neuigkeiten', 'Resets erklärt', 'NEUESTES SIGNAL', 'Quelle lesen', 'Alle', 'Resets', 'Reset-Guthaben', 'Nutzung', 'Unbestätigt', 'Kontingent-Reset', 'Reset-Guthaben', 'Nutzungsänderung', 'Reset-Hinweis', 'Abschluss gemeldet', 'Angekündigt', 'Information', 'Unbestätigt', 'Deine nächste Sitzung', 'Trage die Rücksetzzeit ein, die dein Codex-Konto anzeigt.', 'Timer einstellen', 'Datum und Uhrzeit', 'Timer speichern', 'Timer löschen', 'Zum Kalender hinzufügen', 'Deine nächste Idee wartet hier.', 'Zeit, dein Konto zu prüfen', 'Auf diesem Gerät gespeichert. Maßgeblich ist dein Konto; der Timer kann keinen Reset bestätigen.', 'Quellen geprüft', 'Informationen könnten veraltet sein', 'Einige Quellen sind nicht erreichbar', 'Letzte erfolgreiche Prüfung', 'Keine Meldungen in dieser Kategorie.', 'Weitere Meldungen', 'Teilen', 'Link kopiert', 'Von Shixi Lin', 'Projekt unterstützen', 'Zusammenarbeiten', 'Unabhängiges Open-Source-Projekt. Nicht mit OpenAI verbunden.', 'Ein Reset und Reset-Guthaben sind zwei verschiedene Dinge.', 'Gilt ein öffentlicher Reset auch für mich?', 'Das hängt von der Ankündigung und deinem Tarif ab. Prüfe die Codex-Nutzungsübersicht oder führe /status in der CLI aus. Ein öffentlicher Beitrag bestätigt nicht dein persönliches Restkontingent.', 'Was ist Reset-Guthaben?', 'Ein gespeicherter Reset, den berechtigte Konten später einlösen können. Verfügbarkeit und Umfang hängen vom aktuellen Angebot ab. Beachte die Hinweise in deinem Konto.', 'Lässt sich der nächste Reset vorhersagen?', 'Nein. Öffentliche Ankündigungen, persönliche Nutzungszeiträume und Reset-Guthaben sind verschieden. Der Timer verwendet deine Eingabe und sagt keine OpenAI-Ankündigungen voraus.', 'Woher kommen die Meldungen?', 'Aus öffentlichen Beiträgen von OpenAI und der Codex-Leitung. Ein Community-Feed liefert mögliche Links, die über die offizielle X-Einbettungsschnittstelle geprüft werden. Unvollständige oder mehrdeutige Texte bleiben unbestätigt. Geplante Prüfungen können sich verzögern.', 'Erfasst werden ausgewählte öffentliche Ankündigungen, keine vollständigen Konto- oder Dienststatusdaten.', 'Quellenauszug · Originalsprache', 'Zurück zu den Meldungen', 'Codex-Reset-Verlauf', 'RSS-Feed', 'JSON-Feed', 'Keine Anmeldung. Der Timer bleibt im Browser, die Kalenderdatei auf deinem Gerät.', 'Wähle ein gültiges Datum mit Uhrzeit in der Zukunft.', 'Codex-Reset-Meldungen und persönlicher Timer'
],
ar: [
'نقطة عودة لفكرتك التالية', 'انتهت الحصة.\nوالأفكار مستمرة.', 'تابع إعلانات إعادة تعيين حصة Codex، واحفظ موعد تجدد حصتك، ثم عد إلى مشاريعك.', 'عرض استخدامي', 'إنشاء تذكير', 'المستجدات', 'كيف تعمل إعادة التعيين', 'أحدث إشارة', 'عرض المصدر', 'الكل', 'إعادة التعيين', 'رصيد إعادة التعيين', 'الاستخدام', 'غير مؤكد', 'إعادة تعيين الحصة', 'رصيد إعادة التعيين', 'تحديث الاستخدام', 'إشارة لإعادة التعيين', 'أُعلن عن الاكتمال', 'مُعلن عنه', 'معلومة', 'غير مؤكد', 'جلستك التالية', 'أدخل موعد تجدد الحصة الظاهر في حساب Codex.', 'ضبط المؤقت', 'تاريخ التجدد ووقته', 'حفظ المؤقت', 'مسح المؤقت', 'إضافة إلى التقويم', 'فكرتك التالية تنتظرك هنا.', 'حان وقت التحقق من حسابك', 'يُحفظ على هذا الجهاز. حسابك هو المرجع؛ المؤقت لا يتحقق من اكتمال إعادة التعيين.', 'تم فحص المصادر', 'قد تكون المعلومات قديمة', 'بعض المصادر غير متاحة', 'آخر فحص ناجح', 'لا توجد مستجدات في هذه الفئة.', 'عرض المزيد', 'مشاركة', 'تم نسخ الرابط', 'من صنع Shixi Lin', 'دعم المشروع', 'للتعاون', 'مشروع مستقل ومفتوح المصدر، غير تابع لـOpenAI.', 'إعادة تعيين الحصة ورصيد إعادة التعيين أمران مختلفان.', 'هل تنطبق إعادة التعيين العامة على حسابي؟', 'يتوقف ذلك على الإعلان وخطتك. راجع لوحة استخدام Codex أو نفّذ /status في واجهة الأوامر. المنشور العام لا يؤكد رصيد حسابك الشخصي.', 'ما هو رصيد إعادة التعيين؟', 'هو فرصة محفوظة لإعادة التعيين يمكن للحسابات المؤهلة استخدامها لاحقًا. يتوقف توفرها وما تستعيده من حصة على العرض الحالي. اتبع التعليمات في حسابك.', 'هل يمكن توقع موعد إعادة التعيين التالية؟', 'لا. الإعلانات العامة وفترات الاستخدام الشخصية ورصيد إعادة التعيين أشياء مختلفة. يستخدم المؤقت الوقت الذي تدخله ولا يتنبأ بإعلانات OpenAI.', 'ما مصادر المستجدات؟', 'منشورات OpenAI ومسؤول Codex العامة. تُكتشف الروابط عبر موجز مجتمعي، ثم تُفحص من خلال خدمة التضمين الرسمية لـX. تبقى النصوص الناقصة أو الملتبسة غير مؤكدة. وقد تتأخر الفحوص المجدولة.', 'التغطية تشمل إعلانات عامة مختارة، وليست سجلًا كاملًا للحسابات أو حالة الخدمة.', 'مقتطف من المصدر · باللغة الأصلية', 'العودة إلى المستجدات', 'سجل إعادة تعيين Codex', 'موجز RSS', 'موجز JSON', 'لا يلزم تسجيل الدخول. يبقى المؤقت في متصفحك، ويُنزل ملف التقويم إلى جهازك.', 'اختر تاريخًا ووقتًا صالحين في المستقبل.', 'مستجدات إعادة تعيين Codex ومؤقت شخصي'
]};
export const locales = Object.fromEntries(Object.entries(rows).map(([lang, row]) => {
  if (row.length !== keys.length) throw new Error(`${lang}: ${row.length} translations for ${keys.length} keys`);
  return [lang, Object.fromEntries(keys.map((key, i) => [key, row[i]]))];
}));

const privacy={en:'No login. No account access. Calendar downloads stay on your device.',zh:'无需登录，不读取账号。下载的日历文件留在本机。','zh-Hant':'無需登入，不讀取帳號。下載的行事曆檔案留在本機。',ja:'ログイン不要。アカウントへのアクセスはありません。カレンダーは端末に保存されます。',ko:'로그인이나 계정 접근 없이 사용합니다. 캘린더 파일은 기기에 저장됩니다.',es:'Sin inicio de sesión ni acceso a tu cuenta. Los calendarios se descargan en tu dispositivo.',fr:'Sans connexion ni accès à votre compte. Les calendriers restent sur votre appareil.',de:'Ohne Anmeldung oder Kontozugriff. Kalenderdateien bleiben auf deinem Gerät.',ar:'لا يلزم تسجيل الدخول ولا نصل إلى حسابك. تبقى ملفات التقويم على جهازك.'};
for(const [lang,value] of Object.entries(privacy))locales[lang].privacy=value;

const focusedPrivacy={"en":"No login. No account access. No email collection.","zh":"无需登录，不读取账号，不收集邮箱。","zh-Hant":"無需登入，不讀取帳號，不收集信箱。","ja":"ログイン不要。アカウントやメールアドレスは収集しません。","ko":"로그인이 필요 없으며 계정이나 이메일을 수집하지 않습니다.","es":"Sin inicio de sesión, acceso a cuentas ni recogida de correos.","fr":"Sans connexion, accès aux comptes ni collecte d’adresses e-mail.","de":"Ohne Anmeldung, Kontozugriff oder Erfassung von E-Mail-Adressen.","ar":"لا تسجيل دخول ولا وصول إلى الحساب ولا جمع للبريد الإلكتروني."};
for(const [lang,text]of Object.entries(focusedPrivacy))locales[lang].privacy=text;
