import { escapeHtml as e } from './shared.mjs';
import { platformCopy } from './platform-copy.mjs';
import { resetStatus, countdown } from './reset-status.mjs';
export function platformPanel(platforms,lang,base){
 const t=platformCopy[lang];
 return `<section class="reset-overview"><div class="overview-title"><h1>${e(t.heading)}</h1><img src="${base}assets/mascot.webp" width="72" height="72" alt=""/></div><div class="platform-grid">${Object.entries(platforms).map(([id,p])=>{
 const s=resetStatus(p.reset);return `<article class="platform-card" data-platform="${id}"><div class="platform-heading"><h2>${e(p.name)}</h2><a href="${e(p.profileUrl)}" target="_blank" rel="noopener noreferrer">${id==='codex'?'Tibo · @thsottiaux':'@ClaudeDevs'} ↗</a></div><p class="reset-label">${e(t.next)}</p><div class="public-countdown" data-public-countdown>${s.state==="announced"?(p.reset.approximate?"≈ ":"")+countdown(s.remainingMs):e(t[s.state]||t.unknown)}</div><p class="public-reset-time" data-public-time>${e(t.local)}</p>${p.reset.sourceUrl?`<a class="reset-source" href="${e(p.reset.sourceUrl)}" target="_blank" rel="noopener noreferrer">${e(t.source)} · ${e(p.reset.sourceTimezone||"UTC")} ↗</a>`:""}<div class="gift-summary" data-offer><strong>${e(t.gifts)}</strong>${p.gifts.length?p.gifts.map(g=>`<p>${e(t.boost)}</p><small>${e(t.automatic)}</small><p class="offer-eligibility">${e(t.eligibility)}</p><p class="offer-status" data-offer-status></p><p>${e(t.ends)}: <time datetime="${e(g.endsAt)}">${e(g.endsAt)}</time></p><a href="${e(g.sourceUrl)}" target="_blank" rel="noopener noreferrer">${e(t.source)} ↗</a>`).join(''):p.latestGift?`<p><small>${e(t.latestGift)}</small></p>${p.latestGift.eligiblePlans?.join(",")==="Plus,Pro,Business"?`<p>${e(t.bankedPlans)}</p>`:`<p lang="en" dir="ltr">${e(p.latestGift.excerpt)}</p>`}<p><time datetime="${e(p.latestGift.publishedAt)}">${e(p.latestGift.publishedAt)}</time></p><a href="${e(p.latestGift.sourceUrl)}" target="_blank" rel="noopener noreferrer">${e(t.source)} ↗</a>`:`<p>${e(t.noOffer)}</p>`}</div><a class="text-link" href="${e(p.usageUrl)}" target="_blank" rel="noopener noreferrer">${e(t.usage)} ↗</a></article>`;
 }).join('')}</div></section>`;
}
