import {escapeHtml as e, freshness} from './shared.mjs';
const copy={
en:['Sources checked','Some sources unavailable','Check overdue','Not checked yet','Coverage & update rules','We track quota resets, reset credits, and subscription allowance changes. Model launches, retirements and adoption statistics are excluded unless they also change your allowance.','The latest relevant post is separate from the last reported reset. Plans and hints do not count as completed resets. Countdown timers require an explicit announcement time.','Checks run twice an hour and may be delayed. Codex and Claude are checked independently; an unavailable source means coverage is incomplete. No new matching post does not mean your account has no changes.'],
zh:['来源检查正常','部分来源暂不可用','检查已过期','尚未完成检查','收录与更新规则','收录额度重置、重置卡和订阅额度调整；模型发布、退役及使用人数变化，只有同时涉及额度调整时才收录。','最新相关推文与上次重置分开显示。计划和暗示不算已完成重置；倒计时必须有公告明确给出的时间。','每小时检查两次，实际运行可能延迟。Codex与Claude分别检查，来源不可用时标明覆盖不完整。未发现新的相关消息，不代表你的账号没有变化。'],
'zh-Hant':['來源檢查正常','部分來源暫不可用','檢查已過期','尚未完成檢查','收錄與更新規則','收錄額度重置、重置卡及訂閱額度調整；模型發佈、退役及使用人數變化，只有同時涉及額度調整時才收錄。','最新相關推文與上次重置分開顯示。計畫和暗示不算已完成重置；倒數計時必須有公告明確給出的時間。','每小時檢查兩次，實際執行可能延遲。Codex與Claude分別檢查，來源無法使用時標明涵蓋不完整。未發現新的相關消息，不代表你的帳號沒有變化。'],
ja:['情報源を確認済み','一部の情報源を確認できません','確認情報が古くなっています','未確認','収録・更新ルール','利用枠のリセット、リセット権、契約プランの利用枠変更を収録します。モデルの公開・終了や利用者数の変化は、利用枠の変更を伴う場合のみ対象です。','最新の関連投稿と直近のリセットは別表示です。予定や示唆は完了を意味しません。カウントダウンには明示された告知時刻が必要です。','毎時2回確認しますが、遅延する場合があります。CodexとClaudeは個別に確認し、情報源が利用できない場合は確認範囲が不完全と表示します。新しい関連投稿がなくても、個人のアカウントに変更がないとは限りません。'],
ko:['출처 확인 완료','일부 출처 확인 불가','확인 정보가 오래됨','아직 확인되지 않음','수집 및 업데이트 규칙','사용량 초기화, 초기화 이용권, 구독 한도 변경을 수집합니다. 모델 출시·종료와 이용자 수 변화는 한도 변경을 포함할 때만 수집합니다.','최신 관련 게시물과 마지막 초기화는 별도로 표시합니다. 계획이나 암시는 완료가 아닙니다. 카운트다운에는 공지에 명시된 시간이 필요합니다.','매시간 두 번 확인하며 지연될 수 있습니다. Codex와 Claude를 각각 확인하고 출처를 확인할 수 없으면 불완전한 상태로 표시합니다. 새 관련 게시물이 없다고 개인 계정에 변화가 없는 것은 아닙니다.'],
es:['Fuentes comprobadas','Algunas fuentes no disponibles','Comprobación desactualizada','Sin comprobar','Reglas de selección y actualización','Seguimos restablecimientos, créditos de restablecimiento y cambios en los límites de suscripción. Los lanzamientos, retiradas y cifras de adopción solo se incluyen si también modifican esos límites.','La última publicación relacionada se separa del último restablecimiento anunciado como completado. Los planes e indicios no confirman la finalización. La cuenta atrás requiere una hora explícita en el anuncio.','Comprobamos dos veces por hora, con posibles retrasos. Codex y Claude se comprueban por separado; una fuente no disponible implica cobertura incompleta. La ausencia de publicaciones nuevas no descarta cambios en tu cuenta.'],
fr:['Sources vérifiées','Certaines sources indisponibles','Vérification ancienne','Pas encore vérifié','Règles de sélection et de mise à jour','Nous suivons les réinitialisations, les crédits de réinitialisation et les changements de quotas des abonnements. Les lancements, retraits et chiffres d’adoption ne sont inclus que s’ils modifient aussi ces quotas.','La dernière publication pertinente est distincte de la dernière réinitialisation déclarée terminée. Les projets et indices ne prouvent pas son achèvement. Le compte à rebours exige une heure explicite dans l’annonce.','Deux vérifications par heure, avec des retards possibles. Codex et Claude sont vérifiés séparément ; une source indisponible signifie une couverture incomplète. L’absence de nouvelle publication pertinente n’exclut pas un changement sur votre compte.'],
de:['Quellen geprüft','Einige Quellen nicht verfügbar','Prüfung veraltet','Noch nicht geprüft','Auswahl- und Aktualisierungsregeln','Erfasst werden Resets, Reset-Guthaben und Änderungen der Abonnementlimits. Modellstarts, Abschaltungen und Nutzungszahlen werden nur aufgenommen, wenn sich zugleich das Nutzungskontingent ändert.','Der neueste relevante Beitrag und der letzte als abgeschlossen gemeldete Reset werden getrennt angezeigt. Pläne und Hinweise gelten nicht als Abschluss. Ein Countdown erfordert eine ausdrücklich angekündigte Uhrzeit.','Zwei Prüfungen pro Stunde; Verzögerungen sind möglich. Codex und Claude werden getrennt geprüft. Nicht verfügbare Quellen bedeuten unvollständige Abdeckung. Fehlende neue Beiträge schließen Änderungen am eigenen Konto nicht aus.'],
ar:['تم فحص المصادر','بعض المصادر غير متاحة','الفحص قديم','لم يُفحص بعد','قواعد الاختيار والتحديث','نتابع إعادة ضبط الحصص وأرصدة إعادة الضبط وتغييرات حدود الاشتراك. لا ندرج إطلاق النماذج أو إيقافها أو أعداد مستخدميها إلا إذا شملت تغييرًا في الحصص.','نفصل أحدث منشور ذي صلة عن آخر إعادة ضبط أُعلن اكتمالها. الخطط والتلميحات لا تعني الاكتمال. يتطلب العد التنازلي موعدًا صريحًا في الإعلان.','نفحص مرتين كل ساعة وقد يحدث تأخير. نفحص Codex وClaude بشكل مستقل، ونوضح نقص التغطية عند تعذر الوصول إلى مصدر. عدم العثور على منشور جديد لا يعني عدم وجود تغييرات في حسابك.']
};
export function trackingPanel(health,lang,now=Date.now()) {
 const c=copy[lang]||copy.en;
 return ['codex','claude'].map(id=>{
  const h=health.platforms?.[id],state=h?(!h.lastSuccessAt&&h.status==='degraded'?'degraded':freshness(h,now)):'unknown';
  const label=!h?c[3]:state==='stale'?c[2]:state==='degraded'?c[1]:c[0];
  const at=h?.lastAttemptAt;
  const date=at?new Intl.DateTimeFormat(lang,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZoneName:'shortOffset'}).format(new Date(at)):'';
  return `<div class="platform-check" data-check-platform="${id}" data-state="${state}"><span><strong>${id==='codex'?'Codex':'Claude'}</strong> · ${e(label)}</span>${at?`<time datetime="${e(at)}">${e(date)}</time>`:''}</div>`;
 }).join('');
}
export function trackingRules(lang){const c=copy[lang]||copy.en;return `<details class="tracking-rules"><summary>${e(c[4])}</summary>${c.slice(5).map(text=>`<p>${e(text)}</p>`).join('')}</details>`;}
