const rows={
 en:['Last successful check','Check unavailable; showing the last saved update.','Reset credit','Extra usage','Reset credit announcement','Eligible plans','How it works','Follow the announcement to claim or redeem.','Announcement posted','End date','Standard weekly limits only; 5-hour limits are unchanged.','Previous reset announcement','Sources have not been checked recently.'],
 zh:['上次成功检查','暂时无法检查，保留上次记录。','重置卡','额外额度','重置卡赠送公告','适用方案','使用方式','领取或使用方式以公告为准。','公告时间','截止时间','仅调整每周额度，5小时额度不变。','上次重置公告','已有一段时间未完成检查。'],
 'zh-Hant':['上次成功檢查','暫時無法檢查，保留上次記錄。','重置卡','額外額度','重置卡贈送公告','適用方案','使用方式','領取或使用方式以公告為準。','公告時間','截止時間','僅調整每週額度，5小時額度不變。','上次重置公告','已有一段時間未完成檢查。'],
 ja:['最終確認','確認できないため、前回の情報を表示しています。','リセット権','追加利用枠','リセット権の付与案内','対象プラン','利用方法','受け取り・利用方法は告知をご確認ください。','告知日時','終了日時','週間利用枠のみ変更。5時間の上限は変わりません。','前回のリセット完了発表','しばらく情報を確認できていません。'],
 ko:['마지막 확인','확인할 수 없어 이전 정보를 표시합니다.','초기화 이용권','추가 사용량','초기화 이용권 지급 안내','대상 요금제','이용 방법','수령 또는 사용 방법은 공지를 확인하세요.','공지 시간','종료 시간','주간 한도만 변경되며 5시간 한도는 그대로입니다.','최근 초기화 완료 공지','최근 정보 확인이 이루어지지 않았습니다.'],
 es:['Última comprobación correcta','No se pudo comprobar; se muestra la última información guardada.','Crédito de restablecimiento','Uso extra','Anuncio de créditos de restablecimiento','Planes elegibles','Cómo funciona','Consulta el anuncio para obtener o canjear el crédito.','Fecha del anuncio','Fecha de fin','Solo límites semanales; los límites de 5 horas no cambian.','Último anuncio de restablecimiento','Hace tiempo que no se comprueban las fuentes.'],
 fr:['Dernière vérification réussie','Vérification indisponible ; les dernières données sont conservées.','Crédit de réinitialisation','Usage supplémentaire','Annonce de crédits de réinitialisation','Offres éligibles','Utilisation','Consultez l’annonce pour obtenir ou utiliser le crédit.','Date de l’annonce','Date de fin','Limites hebdomadaires uniquement ; les limites de 5 heures ne changent pas.','Dernière annonce de réinitialisation','Les sources n’ont pas été vérifiées récemment.'],
 de:['Zuletzt erfolgreich geprüft','Prüfung nicht möglich; der letzte gespeicherte Stand wird angezeigt.','Reset-Guthaben','Zusätzliche Nutzung','Ankündigung von Reset-Guthaben','Berechtigte Tarife','Verwendung','Einlösung und Nutzung richten sich nach der Ankündigung.','Veröffentlicht','Endet am','Nur Wochenlimits; die 5-Stunden-Limits bleiben unverändert.','Letzte Reset-Abschlussmeldung','Die Quellen wurden länger nicht geprüft.'],
 ar:['آخر تحقق ناجح','تعذّر التحقق؛ تُعرض آخر معلومات محفوظة.','رصيد إعادة ضبط','استخدام إضافي','إعلان منح رصيد إعادة ضبط','الخطط المؤهلة','طريقة الاستخدام','راجع الإعلان لمعرفة طريقة الحصول على الرصيد أو استخدامه.','وقت الإعلان','موعد الانتهاء','الحدود الأسبوعية فقط؛ حدود الساعات الخمس لم تتغير.','آخر إعلان لاكتمال إعادة الضبط','لم تُفحص المصادر مؤخرًا.']
};
const keys=['checked','failed','credit','extra','creditTitle','plans','how','redeem','posted','ends','weeklyOnly','lastReset','stale'];
export const visitorCopy=Object.fromEntries(Object.entries(rows).map(([lang,values])=>[lang,Object.fromEntries(keys.map((key,i)=>[key,values[i]]))]));
