const keys=['intro','waiting','last','noHistory','watch','watching','note','newReset','changed','refresh','offline','updated'];
const rows={
en:['Public resets. Extra usage. Back to building.','Waiting for an announcement','Latest confirmed reset','No verified reset recorded yet','Notify me','Watching for updates','Keep this page open. Alerts follow verified announcements automatically; background tabs may delay delivery.','A new reset has been confirmed. Check your usage.','The reset announcement has changed.','Check for updates','Connection interrupted · showing the last checked data','Page data updated'],
zh:['重置消息、额外额度，及时掌握。','等待新的重置公告','最近确认的重置','尚无已核实的重置记录','有消息提醒我','正在关注更新','保持网页打开，提醒会自动跟随已核实的公告；后台标签页可能延迟提醒。','已确认新的重置，请查看你的额度。','重置公告有更新。','检查更新','连接中断，暂时显示上次核查的数据','页面数据已更新'],
'zh-Hant':['掌握重置消息與額外額度。','等待新的重置公告','最近確認的重置','尚無已核實的重置記錄','有消息提醒我','正在關注更新','保持網頁開啟，提醒會自動跟隨已核實的公告；背景分頁可能延遲提醒。','已確認新的重置，請查看你的額度。','重置公告有更新。','檢查更新','連線中斷，顯示上次查核的資料','頁面資料已更新'],
ja:['リセット情報と追加利用枠を、ひと目で。','新しい発表を待っています','直近の確認済みリセット','確認済みの記録はまだありません','更新を知らせる','更新を確認中','このページを開いたままにしてください。確認済みの発表に合わせて通知します。背景のタブでは遅れる場合があります。','新たなリセットが確認されました。利用状況をご確認ください。','リセットの発表が更新されました。','更新を確認','接続が中断しました。前回の確認結果を表示中','ページ情報を更新しました'],
ko:['초기화 소식과 추가 사용량을 한눈에.','새로운 발표를 기다리는 중','최근 확인된 초기화','확인된 초기화 기록이 없습니다','업데이트 알림 받기','업데이트 확인 중','페이지를 열어 두세요. 확인된 발표에 따라 자동으로 알립니다. 백그라운드 탭에서는 알림이 늦어질 수 있습니다.','새로운 초기화가 확인되었습니다. 사용량을 확인하세요.','초기화 발표가 변경되었습니다.','업데이트 확인','연결이 끊겼습니다. 마지막 확인 데이터를 표시합니다','페이지 데이터 업데이트됨'],
es:['Restablecimientos y uso extra, de un vistazo.','A la espera de un nuevo anuncio','Último restablecimiento confirmado','Aún no hay registros verificados','Avisarme','Siguiendo las novedades','Mantén esta página abierta. Las alertas siguen los anuncios verificados; pueden retrasarse en pestañas en segundo plano.','Se ha confirmado un nuevo restablecimiento. Consulta tu uso.','El anuncio ha cambiado.','Buscar novedades','Conexión interrumpida · últimos datos comprobados','Datos de la página actualizados'],
fr:['Réinitialisations et usage supplémentaire, en un coup d’œil.','En attente d’une nouvelle annonce','Dernière réinitialisation confirmée','Aucune réinitialisation vérifiée pour le moment','Me prévenir','Suivi des annonces activé','Gardez cette page ouverte. Les alertes suivent les annonces vérifiées ; elles peuvent être retardées en arrière-plan.','Une nouvelle réinitialisation est confirmée. Vérifiez votre utilisation.','L’annonce a été modifiée.','Actualiser','Connexion interrompue · dernières données vérifiées','Données de la page actualisées'],
de:['Resets und zusätzliche Nutzung auf einen Blick.','Warten auf eine neue Ankündigung','Letzter bestätigter Reset','Noch kein bestätigter Reset erfasst','Benachrichtigen','Updates werden verfolgt','Lass diese Seite geöffnet. Hinweise folgen bestätigten Ankündigungen; in Hintergrund-Tabs können sie verspätet erscheinen.','Ein neuer Reset wurde bestätigt. Prüfe deine Nutzung.','Die Reset-Ankündigung wurde geändert.','Nach Updates suchen','Verbindung unterbrochen · zuletzt geprüfte Daten','Seitendaten aktualisiert'],
ar:['إعادة الضبط والاستخدام الإضافي، في مكان واحد.','بانتظار إعلان جديد','آخر إعادة ضبط مؤكدة','لا توجد سجلات مؤكدة بعد','أبلغني بالتحديثات','متابعة التحديثات مفعّلة','أبقِ هذه الصفحة مفتوحة. تتبع التنبيهات الإعلانات الموثّقة تلقائيًا؛ وقد تتأخر في علامات التبويب الخلفية.','تأكدت إعادة ضبط جديدة. تحقق من استخدامك.','تغيّر إعلان إعادة الضبط.','التحقق من التحديثات','انقطع الاتصال · تُعرض آخر بيانات تم التحقق منها','تم تحديث بيانات الصفحة']
};
export const watchCopy=Object.fromEntries(Object.entries(rows).map(([lang,row])=>[lang,Object.fromEntries(keys.map((key,i)=>[key,row[i]]))]));

const focusedIntros={"en": "Reset times. Latest offers. Recent news.", "zh": "重置时间、最新方案、近期消息。", "zh-Hant": "重置時間、最新方案、近期消息。", "ja": "リセット時刻、最新の特典、最近のお知らせ。", "ko": "초기화 시간, 최신 혜택, 최근 소식.", "es": "Horarios de restablecimiento, últimas ofertas y noticias recientes.", "fr": "Horaires de réinitialisation, dernières offres et actualités.", "de": "Reset-Zeiten. Aktuelle Angebote. Neueste Meldungen.", "ar": "مواعيد إعادة الضبط، أحدث العروض، وآخر الأخبار."};
for(const [lang,text]of Object.entries(focusedIntros))watchCopy[lang].intro=text;
